import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getCourseById, updateCourse } from "../services/courseService";
import { createAssessment, getAssessmentsByCourse, updateAssessment } from "../services/assessmentService";
import { createAssignment, getAssignmentsByCourse, updateAssignment, deleteAssignment } from "../services/assignmentService";
import AssessmentFormModal from "../components/AssessmentFormModal";
import AssignmentFormModal from "../components/AssignmentFormModal";
import EditableSyllabus from "../components/EditableSyllabus";
import EditableStudyMaterial from "../components/EditableStudyMaterial";
import EditableAssessment from "../components/EditableAssessment";
import EditableAssignment from "../components/EditableAssignment";
import MathText from "../components/MathText";
import Toast from "../components/Toast";
import AppShell from "../components/layout/AppShell";
import Icon from "../components/ui/Icon";
import useModalFocus from "../hooks/useModalFocus";
import { generateSyllabusPDF, generateStudyMaterialPDF, generateQuestionPaperPDF, generateAnswerKeyPDF, generateAssignmentPDF, generateAssignmentAnswerKeyPDF } from "../utils/pdfGenerator";
import "../course-detail.css";

const tabs = [
  { id:"syllabus", label:"Syllabus", icon:"layers" },
  { id:"material", label:"Study material", icon:"book" },
  { id:"assessment", label:"Assessments", icon:"file" },
  { id:"assignment", label:"Assignments", icon:"check" },
];
const formatDate = value => value ? new Date(value).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}) : "Not recorded";
const difficultyClass = value => `detail-level ${String(value||"adaptive").toLowerCase()}`;

function DetailSkeleton(){return <AppShell><div className="detail-page detail-loading" role="status" aria-label="Loading course"><div className="detail-skeleton hero"/><div className="detail-skeleton tabs"/><div className="detail-skeleton content"/></div></AppShell>}
function EmptyPanel({icon,title,copy,action,label}){return <div className="detail-empty"><span><Icon name={icon} size={22}/></span><h3>{title}</h3><p>{copy}</p>{action&&<button className="detail-button primary" onClick={action}><Icon name="spark" size={14}/>{label}</button>}</div>}
function ExportButton({onClick,label="Export PDF"}){return <button className="detail-button secondary" onClick={onClick}><Icon name="file" size={14}/>{label}</button>}

export default function CourseDetail(){
  const {id}=useParams(); const navigate=useNavigate();
  const [course,setCourse]=useState(null); const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState("");
  const [activeTab,setActiveTab]=useState("syllabus"); const [editMode,setEditMode]=useState(false);
  const [assessments,setAssessments]=useState([]); const [loadingAssessments,setLoadingAssessments]=useState(true); const [assessmentModal,setAssessmentModal]=useState(false); const [generatingAssessment,setGeneratingAssessment]=useState(false); const [activeAssessment,setActiveAssessment]=useState(null); const [assessmentView,setAssessmentView]=useState("paper");
  const [assignments,setAssignments]=useState([]); const [loadingAssignments,setLoadingAssignments]=useState(true); const [assignmentModal,setAssignmentModal]=useState(false); const [generatingAssignment,setGeneratingAssignment]=useState(false); const [activeAssignment,setActiveAssignment]=useState(null); const [assignmentView,setAssignmentView]=useState("paper");
  const [deleteTarget,setDeleteTarget]=useState(null);
  const [success,setSuccess]=useState(""); const [error,setError]=useState("");

  useEffect(()=>{let mounted=true;(async()=>{try{const data=await getCourseById(id);if(!mounted)return;const next={...data.course};if(Array.isArray(next.studyMaterial))next.studyMaterial=next.studyMaterial[0]||{};setCourse(next)}catch{if(mounted)setLoadError("This course could not be loaded. It may have been removed or your session may have expired.")}finally{if(mounted)setLoading(false)}})();return()=>{mounted=false}},[id]);
  useEffect(()=>{let mounted=true;getAssessmentsByCourse(id).then(data=>{if(!mounted)return;const list=data.assessments||[];setAssessments(list);setActiveAssessment(list[0]||null)}).catch(()=>mounted&&setError("Assessment history could not be loaded.")).finally(()=>mounted&&setLoadingAssessments(false));return()=>{mounted=false}},[id]);
  useEffect(()=>{let mounted=true;getAssignmentsByCourse(id).then(data=>{if(!mounted)return;const list=data.assignments||[];setAssignments(list);setActiveAssignment(list[0]||null)}).catch(()=>mounted&&setError("Assignment history could not be loaded.")).finally(()=>mounted&&setLoadingAssignments(false));return()=>{mounted=false}},[id]);

  const moduleCount=course?.syllabus?.length||0;
  const topicCount=useMemo(()=>course?.syllabus?.reduce((n,w)=>n+(w.topics?.length||0),0)||0,[course]);
  const exportSafely=(fn,message)=>{try{fn();setSuccess(message)}catch{setError("The PDF could not be prepared. Refresh the page and try again.")}};
  const saveSyllabus=async syllabus=>{try{const data=await updateCourse(id,{syllabus});setCourse(prev=>({...prev,syllabus:data.course.syllabus}));setSuccess("Syllabus changes saved.")}catch{setError("Syllabus changes could not be saved.")}};
  const saveMaterial=async studyMaterial=>{try{const data=await updateCourse(id,{studyMaterial});setCourse(prev=>({...prev,studyMaterial:data.course.studyMaterial}));setSuccess("Study material changes saved.")}catch{setError("Study material changes could not be saved.")}};
  const refreshAssessments=async()=>{const data=await getAssessmentsByCourse(id);const list=data.assessments||[];setAssessments(list);setActiveAssessment(list[0]||null);return list};
  const generateAssessment=async form=>{setGeneratingAssessment(true);try{const data=await createAssessment({...form,courseId:id});await refreshAssessments();setAssessmentModal(false);setAssessmentView("paper");setSuccess(data.isFallback?"A complete sample assessment was prepared while AI capacity was limited.":"Assessment generated and added to this course.")}catch(e){setError(e.userMessage||e.response?.data?.message||"Assessment generation did not complete.")}finally{setGeneratingAssessment(false)}};
  const saveAssessment=async updates=>{try{const data=await updateAssessment(activeAssessment._id,updates);setAssessments(prev=>prev.map(a=>a._id===activeAssessment._id?data.assessment:a));setActiveAssessment(data.assessment);setSuccess("Assessment changes saved.")}catch{setError("Assessment changes could not be saved.")}};
  const refreshAssignments=async()=>{const data=await getAssignmentsByCourse(id);const list=data.assignments||[];setAssignments(list);setActiveAssignment(list[0]||null);return list};
  const generateAssignment=async form=>{setGeneratingAssignment(true);try{const data=await createAssignment({...form,courseId:id});const list=await refreshAssignments();setActiveAssignment(list.find(a=>a._id===data.assignment?._id)||data.assignment||list[0]);setAssignmentModal(false);setAssignmentView("paper");setSuccess(data.isFallback?"A complete sample assignment was prepared while AI capacity was limited.":"Assignment generated and added to this course.")}catch(e){setError(e.userMessage||e.response?.data?.message||"Assignment generation did not complete.")}finally{setGeneratingAssignment(false)}};
  const saveAssignment=async updates=>{try{const data=await updateAssignment(activeAssignment._id,updates);setAssignments(prev=>prev.map(a=>a._id===activeAssignment._id?data.assignment:a));setActiveAssignment(data.assignment);setSuccess("Assignment changes saved.")}catch{setError("Assignment changes could not be saved.")}};
  const removeAssignment=async()=>{if(!deleteTarget)return;const assignmentId=deleteTarget._id;setDeleteTarget(null);try{await deleteAssignment(assignmentId);const list=await refreshAssignments();setActiveAssignment(list[0]||null);setSuccess("Assignment deleted.")}catch{setError("The assignment could not be deleted.")}};

  if(loading)return <DetailSkeleton/>;
  if(loadError||!course)return <AppShell><div className="detail-page"><EmptyPanel icon="book" title="Course unavailable" copy={loadError||"This course could not be found."} action={()=>navigate("/")} label="Return to course library"/></div></AppShell>;

  const materialSections=[
    {key:"keyConcepts",label:"Key concepts",number:"01"},{key:"definitions",label:"Definitions",number:"02"},{key:"realWorldExamples",label:"Applied examples",number:"03"},{key:"interviewQuestions",label:"Review questions",number:"04"},{key:"furtherReading",label:"Further reading",number:"05"},
  ];

  return <AppShell><div className="detail-page">
    <button className="detail-back" onClick={()=>navigate("/")}><Icon name="arrow" size={15}/>Course library</button>
    <section className="detail-hero"><div className="detail-hero-copy"><span className="detail-eyebrow"><Icon name="spark" size={12}/>AI-GENERATED COURSE</span><h1>{course.title}</h1><p>{course.studyMaterial?.summary||`A structured ${course.difficulty?.toLowerCase()||"adaptive"} learning path designed for ${course.audience||"focused learners"}.`}</p><div className="detail-tags"><span className={difficultyClass(course.difficulty)}>{course.difficulty||"Adaptive"}</span><span><Icon name="clock" size={13}/>{course.duration||"Self paced"}</span><span><Icon name="file" size={13}/>Created {formatDate(course.createdAt)}</span></div></div><div className="detail-hero-side"><div className="course-health"><span>COURSE STRUCTURE</span><strong>{moduleCount}</strong><small>modules · {topicCount} focused topics</small><i><b style={{width:`${Math.min(100,Math.max(18,moduleCount*10))}%`}}/></i></div><button className={`detail-button ${editMode?"editing":"secondary"}`} onClick={()=>setEditMode(v=>!v)}><Icon name="settings" size={14}/>{editMode?"Finish editing":"Edit course"}</button></div></section>

    <nav className="detail-tabs" aria-label="Course sections">{tabs.map(tab=><button key={tab.id} className={activeTab===tab.id?"active":""} onClick={()=>setActiveTab(tab.id)}><Icon name={tab.icon} size={15}/>{tab.label}{tab.id==="assessment"&&assessments.length>0&&<span>{assessments.length}</span>}{tab.id==="assignment"&&assignments.length>0&&<span>{assignments.length}</span>}</button>)}</nav>

    <section className="detail-content">
      {activeTab==="syllabus"&&<div className="detail-section"><header className="detail-section-head"><div><span className="detail-kicker">Course progression</span><h2>A syllabus built to develop understanding</h2><p>Each module advances the topic in a deliberate sequence. Use edit mode to revise module names or individual topics.</p></div><ExportButton onClick={()=>exportSafely(()=>generateSyllabusPDF(course),"Syllabus PDF prepared.")}/></header>{editMode?<div className="detail-editor"><EditableSyllabus syllabus={course.syllabus||[]} onChange={saveSyllabus}/></div>:course.syllabus?.length?<div className="modern-timeline">{course.syllabus.map((module,index)=><article key={`${module.week}-${index}`}><div className="timeline-marker"><span>{String(index+1).padStart(2,"0")}</span></div><div className="timeline-card"><div><span>MODULE {String(index+1).padStart(2,"0")}</span><h3>{module.week}</h3></div><ul>{module.topics?.map((topic,i)=><li key={i}><i/><MathText text={String(topic)}/></li>)}</ul></div></article>)}</div>:<EmptyPanel icon="layers" title="No syllabus modules yet" copy="Add the first module in edit mode to begin structuring this course."/>}</div>}

      {activeTab==="material"&&<div className="detail-section"><header className="detail-section-head"><div><span className="detail-kicker">Study material</span><h2>Concepts organized for review and recall</h2><p>Read the generated explanation, examples and review prompts. Mathematical notation remains rendered with KaTeX.</p></div><ExportButton onClick={()=>exportSafely(()=>generateStudyMaterialPDF(course),"Study material PDF prepared.")}/></header>{editMode?<div className="detail-editor"><EditableStudyMaterial studyMaterial={course.studyMaterial||{}} onChange={saveMaterial}/></div>:course.studyMaterial?<div className="material-layout">{course.studyMaterial.summary&&<article className="material-summary"><span>COURSE SUMMARY</span><p><MathText text={course.studyMaterial.summary}/></p></article>}<div className="material-sections">{materialSections.map(section=>course.studyMaterial?.[section.key]?.length?<article key={section.key}><header><span>{section.number}</span><h3>{section.label}</h3></header><ul>{course.studyMaterial[section.key].map((item,i)=><li key={i}><MathText text={String(item)}/></li>)}</ul></article>:null)}</div></div>:<EmptyPanel icon="book" title="Study material is not available" copy="Generate or add material before exporting this course."/>}</div>}

      {activeTab==="assessment"&&<div className="detail-section"><header className="detail-section-head"><div><span className="detail-kicker">Assessment studio</span><h2>Measure recall, application and analysis</h2><p>Create balanced question papers with explicit marks, difficulty and Bloom's Taxonomy levels.</p></div><button className="detail-button primary" onClick={()=>setAssessmentModal(true)}><Icon name="spark" size={14}/>New assessment</button></header>{loadingAssessments?<div className="detail-inline-loading">Loading assessment history…</div>:!assessments.length?<EmptyPanel icon="file" title="No assessment has been generated" copy="Choose the covered modules, question counts, marks and cognitive levels for the first paper." action={()=>setAssessmentModal(true)} label="Design an assessment"/>:<div className="studio-layout"><aside className="studio-history"><span>ASSESSMENT HISTORY</span>{assessments.map((item,index)=><button key={item._id} className={activeAssessment?._id===item._id?"active":""} onClick={()=>{setActiveAssessment(item);setAssessmentView("paper")}}><strong>Assessment {assessments.length-index}</strong><small>{item.totalMarks||0} marks · {formatDate(item.createdAt)}</small></button>)}</aside>{activeAssessment&&<article className="studio-paper"><header><div><span>ASSESSMENT {assessmentView==="paper"?"PAPER":"ANSWER KEY"}</span><h3>{course.title}</h3><p>{activeAssessment.totalMarks||0} total marks · {activeAssessment.mcqs?.length||0} MCQs · {activeAssessment.shortQuestions?.length||0} short · {activeAssessment.longQuestions?.length||0} long</p></div><div className="paper-actions"><div className="view-switch"><button className={assessmentView==="paper"?"active":""} onClick={()=>setAssessmentView("paper")}>Questions</button><button className={assessmentView==="answers"?"active":""} onClick={()=>setAssessmentView("answers")}>Answers</button></div><ExportButton label={assessmentView==="paper"?"Question PDF":"Answer PDF"} onClick={()=>exportSafely(()=>assessmentView==="paper"?generateQuestionPaperPDF(course,activeAssessment):generateAnswerKeyPDF(course,activeAssessment),"Assessment PDF prepared.")}/></div></header>{editMode?<EditableAssessment assessment={activeAssessment} onSave={saveAssessment}/>:<AssessmentPaper assessment={activeAssessment} showAnswers={assessmentView==="answers"}/>}</article>}</div>}</div>}

      {activeTab==="assignment"&&<div className="detail-section"><header className="detail-section-head"><div><span className="detail-kicker">Applied work</span><h2>Turn course concepts into practical tasks</h2><p>Create assignments with clear marks, due dates and model answers for consistent review.</p></div><button className="detail-button primary" onClick={()=>setAssignmentModal(true)}><Icon name="spark" size={14}/>New assignment</button></header>{loadingAssignments?<div className="detail-inline-loading">Loading assignment history…</div>:!assignments.length?<EmptyPanel icon="check" title="No assignment has been created" copy="Define the task format, covered modules, marks and expected cognitive level." action={()=>setAssignmentModal(true)} label="Create an assignment"/>:<div className="studio-layout"><aside className="studio-history"><span>ASSIGNMENT HISTORY</span>{assignments.map(item=><button key={item._id} className={activeAssignment?._id===item._id?"active":""} onClick={()=>{setActiveAssignment(item);setAssignmentView("paper")}}><strong>{item.title||"Course assignment"}</strong><small>{item.totalMarks||0} marks · {formatDate(item.createdAt)}</small></button>)}</aside>{activeAssignment&&<article className="studio-paper"><header><div><span>COURSE ASSIGNMENT</span><h3>{activeAssignment.title}</h3><p>{activeAssignment.totalMarks||0} total marks{activeAssignment.dueDate?` · Due ${formatDate(activeAssignment.dueDate)}`:" · No due date set"}</p></div><div className="paper-actions"><div className="view-switch"><button className={assignmentView==="paper"?"active":""} onClick={()=>setAssignmentView("paper")}>Questions</button><button className={assignmentView==="answers"?"active":""} onClick={()=>setAssignmentView("answers")}>Answers</button></div><ExportButton label={assignmentView==="paper"?"Assignment PDF":"Answer PDF"} onClick={()=>exportSafely(()=>assignmentView==="paper"?generateAssignmentPDF(course,activeAssignment):generateAssignmentAnswerKeyPDF(course,activeAssignment),"Assignment PDF prepared.")}/><button className="icon-danger" onClick={()=>setDeleteTarget(activeAssignment)} aria-label="Delete assignment">×</button></div></header>{editMode?<EditableAssignment assignment={activeAssignment} onSave={saveAssignment}/>:<AssignmentPaper assignment={activeAssignment} showAnswers={assignmentView==="answers"}/>}</article>}</div>}</div>}
    </section>
  </div>{assessmentModal&&<AssessmentFormModal syllabus={course.syllabus||[]} onClose={()=>setAssessmentModal(false)} onSubmit={generateAssessment} loading={generatingAssessment}/>} {assignmentModal&&<AssignmentFormModal syllabus={course.syllabus||[]} onClose={()=>setAssignmentModal(false)} onSubmit={generateAssignment} loading={generatingAssignment}/>} {deleteTarget&&<ConfirmDialog title="Delete this assignment?" copy={`“${deleteTarget.title||"Course assignment"}” and its generated answers will be removed permanently.`} onCancel={()=>setDeleteTarget(null)} onConfirm={removeAssignment}/>}<Toast message={success} type="success" onDismiss={()=>setSuccess("")}/><Toast message={error} type="error" onDismiss={()=>setError("")}/></AppShell>;
}

function ConfirmDialog({title,copy,onCancel,onConfirm}){
  const dialogRef=useModalFocus(onCancel,false);
  return <div className="brand-dialog-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)onCancel()}}><section ref={dialogRef} className="brand-dialog" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" aria-describedby="confirm-copy"><span className="brand-dialog-icon">!</span><h2 id="confirm-title">{title}</h2><p id="confirm-copy">{copy}</p><div><button className="brand-dialog-cancel" onClick={onCancel}>Keep assignment</button><button className="brand-dialog-danger" onClick={onConfirm}>Delete permanently</button></div></section></div>;
}

function AssessmentPaper({assessment,showAnswers}){
  const groups=[{title:"Section A · Multiple choice",items:assessment.mcqs||[],type:"mcq",marks:assessment.config?.mcqMarks},{title:"Section B · Short answer",items:assessment.shortQuestions||[],type:"qa",marks:assessment.config?.shortMarks},{title:"Section C · Extended response",items:assessment.longQuestions||[],type:"qa",marks:assessment.config?.longMarks}];
  return <div className="question-groups">{groups.map(group=>group.items.length?<section key={group.title}><header><h4>{group.title}</h4><span>{group.marks||0} marks each</span></header>{group.items.map((item,index)=><article className="question-item" key={index}><div className="question-number">{String(index+1).padStart(2,"0")}</div><div><h5><MathText text={item.question}/></h5>{group.type==="mcq"&&<div className="question-options">{item.options?.map((option,i)=><span className={showAnswers&&option===item.correctAnswer?"correct":""} key={i}><b>{String.fromCharCode(65+i)}</b><MathText text={option}/></span>)}</div>}{showAnswers&&group.type==="qa"&&<div className="model-answer"><span>MODEL ANSWER</span><MathText text={item.modelAnswer||"No model answer provided."}/></div>}<div className="question-meta"><span>{item.difficulty||"Adaptive"}</span><span>{item.bloomLevel||"Understanding"}</span></div></div></article>)}</section>:null)}</div>;
}
function AssignmentPaper({assignment,showAnswers}){
  return <div className="question-groups"><section><header><h4>{assignment.description||"Assignment questions"}</h4><span>{assignment.questions?.length||0} questions</span></header>{assignment.questions?.map((item,index)=><article className="question-item" key={index}><div className="question-number">{String(index+1).padStart(2,"0")}</div><div><h5><MathText text={item.question}/></h5>{item.type==="mcq"&&<div className="question-options">{item.options?.map((option,i)=><span className={showAnswers&&option===item.correctAnswer?"correct":""} key={i}><b>{String.fromCharCode(65+i)}</b><MathText text={option}/></span>)}</div>}{showAnswers&&item.type!=="mcq"&&<div className="model-answer"><span>MODEL ANSWER</span><MathText text={item.modelAnswer||"No model answer provided."}/></div>}<div className="question-meta"><span>{item.marks||0} marks</span><span>{item.difficulty||"Adaptive"}</span><span>{item.bloomLevel||"Application"}</span></div></div></article>)}</section></div>;
}
